name: dc-tool

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      fail-fast: false # Don't abort if one matrix dimension fails.
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install libelf
    - name: Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install libelf-dev
    - name: build dc-tool
      run: make dc-tool
