name: dc-tool

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    - name: macOS dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install libelf
    - name: Ubuntu dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install libelf-dev
    - name: build dc-tool
      run: make dc-tool
    - name: build dc-tool-ip
      run: make ip/dc-tool
    - name: build dc-tool-ser
      run: make serial/dc-tool
